Ingorer arena deltakelser opprettet utenfor arena
navikt/aktivitet-arena-acl pull request #108
Opened 2024-09-06 07:28 UTC by tu55eladd

2024-09-06 07:29 UTC, tu55eladd commented
Burde vi håndtere at deltakelser først kommer uten eksternId så med eksternId?

2024-09-09 09:55 UTC, holymaloney requested changes

2024-09-09 09:55 UTC, holymaloney commented on src/main/kotlin/no/nav/arena_tiltak_aktivitet_acl/processors/DeltakerProcessor.kt
> +			throw IgnoredException("Deltakelse opprettet utenfor arena ${this.regUser}")
Hvorfor regUser? arenaId + eksternId er mer relevant å spare på.

2024-09-09 13:00 UTC, tu55eladd commented on src/main/kotlin/no/nav/arena_tiltak_aktivitet_acl/processors/DeltakerProcessor.kt
> +			throw IgnoredException("Deltakelse opprettet utenfor arena ${this.regUser}")
RegUser inneholder hvilket team som sendte endringen, var derfor det kunne være interessant

2024-09-13 14:01 UTC, merged